# Development environment overrides
global:
  environment: development
  domain: dev.wearforce-clean.local
  image:
    tag: develop
    pullPolicy: Always

# Reduced resources for development
gateway:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  autoscaling:
    enabled: false

# AI Services with minimal resources
aiServices:
  llm:
    replicaCount: 1
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
        nvidia.com/gpu: 1
      requests:
        cpu: 500m
        memory: 2Gi
        nvidia.com/gpu: 1
    autoscaling:
      enabled: false

  nlu:
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    autoscaling:
      enabled: false

  rag:
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    autoscaling:
      enabled: false

  stt:
    replicaCount: 1
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi

  tts:
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

# Business Services with minimal resources
businessServices:
  graphql:
    replicaCount: 1
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi
    autoscaling:
      enabled: false

  crm:
    replicaCount: 1
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi
    autoscaling:
      enabled: false

  erp:
    replicaCount: 1
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi
    autoscaling:
      enabled: false

  notification:
    replicaCount: 1
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi
    autoscaling:
      enabled: false

# Infrastructure with minimal resources
infrastructure:
  postgresql:
    primary:
      persistence:
        size: 10Gi
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
    readReplicas:
      replicaCount: 0  # No read replicas in dev

  redis:
    master:
      persistence:
        size: 2Gi
      resources:
        limits:
          cpu: 250m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 128Mi
    replica:
      replicaCount: 0  # No replicas in dev

  qdrant:
    replicaCount: 1
    persistence:
      size: 5Gi
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

# Disable TLS in development
ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: []

# Minimal monitoring
monitoring:
  prometheus:
    server:
      persistentVolume:
        size: 5Gi
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi

  grafana:
    persistence:
      size: 1Gi
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi

# Disable backup in development
backup:
  enabled: false