// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: chat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_OFFLINE   UserStatus = 0
	UserStatus_ONLINE    UserStatus = 1
	UserStatus_AWAY      UserStatus = 2
	UserStatus_BUSY      UserStatus = 3
	UserStatus_INVISIBLE UserStatus = 4
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
		2: "AWAY",
		3: "BUSY",
		4: "INVISIBLE",
	}
	UserStatus_value = map[string]int32{
		"OFFLINE":   0,
		"ONLINE":    1,
		"AWAY":      2,
		"BUSY":      3,
		"INVISIBLE": 4,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

type UserRole int32

const (
	UserRole_MEMBER    UserRole = 0
	UserRole_MODERATOR UserRole = 1
	UserRole_ADMIN     UserRole = 2
	UserRole_OWNER     UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "MEMBER",
		1: "MODERATOR",
		2: "ADMIN",
		3: "OWNER",
	}
	UserRole_value = map[string]int32{
		"MEMBER":    0,
		"MODERATOR": 1,
		"ADMIN":     2,
		"OWNER":     3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[1].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[1]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

type MessageStatus int32

const (
	MessageStatus_PENDING   MessageStatus = 0
	MessageStatus_SENT      MessageStatus = 1
	MessageStatus_DELIVERED MessageStatus = 2
	MessageStatus_READ      MessageStatus = 3
	MessageStatus_FAILED    MessageStatus = 4
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "PENDING",
		1: "SENT",
		2: "DELIVERED",
		3: "READ",
		4: "FAILED",
	}
	MessageStatus_value = map[string]int32{
		"PENDING":   0,
		"SENT":      1,
		"DELIVERED": 2,
		"READ":      3,
		"FAILED":    4,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[2].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[2]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

type MessageContent_ContentType int32

const (
	MessageContent_TEXT     MessageContent_ContentType = 0
	MessageContent_IMAGE    MessageContent_ContentType = 1
	MessageContent_AUDIO    MessageContent_ContentType = 2
	MessageContent_VIDEO    MessageContent_ContentType = 3
	MessageContent_FILE     MessageContent_ContentType = 4
	MessageContent_LOCATION MessageContent_ContentType = 5
	MessageContent_SYSTEM   MessageContent_ContentType = 6
)

// Enum value maps for MessageContent_ContentType.
var (
	MessageContent_ContentType_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
		2: "AUDIO",
		3: "VIDEO",
		4: "FILE",
		5: "LOCATION",
		6: "SYSTEM",
	}
	MessageContent_ContentType_value = map[string]int32{
		"TEXT":     0,
		"IMAGE":    1,
		"AUDIO":    2,
		"VIDEO":    3,
		"FILE":     4,
		"LOCATION": 5,
		"SYSTEM":   6,
	}
)

func (x MessageContent_ContentType) Enum() *MessageContent_ContentType {
	p := new(MessageContent_ContentType)
	*p = x
	return p
}

func (x MessageContent_ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageContent_ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[3].Descriptor()
}

func (MessageContent_ContentType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[3]
}

func (x MessageContent_ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageContent_ContentType.Descriptor instead.
func (MessageContent_ContentType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12, 0}
}

type SystemContent_SystemMessageType int32

const (
	SystemContent_USER_JOINED   SystemContent_SystemMessageType = 0
	SystemContent_USER_LEFT     SystemContent_SystemMessageType = 1
	SystemContent_USER_PROMOTED SystemContent_SystemMessageType = 2
	SystemContent_USER_DEMOTED  SystemContent_SystemMessageType = 3
	SystemContent_ROOM_CREATED  SystemContent_SystemMessageType = 4
	SystemContent_ROOM_UPDATED  SystemContent_SystemMessageType = 5
)

// Enum value maps for SystemContent_SystemMessageType.
var (
	SystemContent_SystemMessageType_name = map[int32]string{
		0: "USER_JOINED",
		1: "USER_LEFT",
		2: "USER_PROMOTED",
		3: "USER_DEMOTED",
		4: "ROOM_CREATED",
		5: "ROOM_UPDATED",
	}
	SystemContent_SystemMessageType_value = map[string]int32{
		"USER_JOINED":   0,
		"USER_LEFT":     1,
		"USER_PROMOTED": 2,
		"USER_DEMOTED":  3,
		"ROOM_CREATED":  4,
		"ROOM_UPDATED":  5,
	}
)

func (x SystemContent_SystemMessageType) Enum() *SystemContent_SystemMessageType {
	p := new(SystemContent_SystemMessageType)
	*p = x
	return p
}

func (x SystemContent_SystemMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemContent_SystemMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[4].Descriptor()
}

func (SystemContent_SystemMessageType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[4]
}

func (x SystemContent_SystemMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemContent_SystemMessageType.Descriptor instead.
func (SystemContent_SystemMessageType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{15, 0}
}

type JoinChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChatRequest) Reset() {
	*x = JoinChatRequest{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChatRequest) ProtoMessage() {}

func (x *JoinChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChatRequest.ProtoReflect.Descriptor instead.
func (*JoinChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *JoinChatRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinChatRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *JoinChatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type JoinChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ActiveUsers   []*ChatUser            `protobuf:"bytes,4,rep,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChatResponse) Reset() {
	*x = JoinChatResponse{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChatResponse) ProtoMessage() {}

func (x *JoinChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChatResponse.ProtoReflect.Descriptor instead.
func (*JoinChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *JoinChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinChatResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JoinChatResponse) GetActiveUsers() []*ChatUser {
	if x != nil {
		return x.ActiveUsers
	}
	return nil
}

type LeaveChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChatRequest) Reset() {
	*x = LeaveChatRequest{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatRequest) ProtoMessage() {}

func (x *LeaveChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatRequest.ProtoReflect.Descriptor instead.
func (*LeaveChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveChatRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LeaveChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaveChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LeaveChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChatResponse) Reset() {
	*x = LeaveChatResponse{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChatResponse) ProtoMessage() {}

func (x *LeaveChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChatResponse.ProtoReflect.Descriptor instead.
func (*LeaveChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveChatResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SendMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RoomId           string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Content          *MessageContent        `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Mentions         []string               `protobuf:"bytes,5,rep,name=mentions,proto3" json:"mentions,omitempty"`
	ReplyToMessageId string                 `protobuf:"bytes,6,opt,name=reply_to_message_id,json=replyToMessageId,proto3" json:"reply_to_message_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendMessageRequest) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *SendMessageRequest) GetReplyToMessageId() string {
	if x != nil {
		return x.ReplyToMessageId
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SendMessageResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *StreamMessagesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StreamMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamMessagesRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type GetChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=before,proto3" json:"before,omitempty"`
	After         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatHistoryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetChatHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetChatHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatHistoryRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetChatHistoryRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *GetChatHistoryRequest) GetAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.After
	}
	return nil
}

type GetChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetChatHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetChatHistoryResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetChatHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetActiveUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveUsersRequest) Reset() {
	*x = GetActiveUsersRequest{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveUsersRequest) ProtoMessage() {}

func (x *GetActiveUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveUsersRequest.ProtoReflect.Descriptor instead.
func (*GetActiveUsersRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetActiveUsersRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetActiveUsersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetActiveUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*ChatUser            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveUsersResponse) Reset() {
	*x = GetActiveUsersResponse{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveUsersResponse) ProtoMessage() {}

func (x *GetActiveUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveUsersResponse.ProtoReflect.Descriptor instead.
func (*GetActiveUsersResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GetActiveUsersResponse) GetUsers() []*ChatUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetActiveUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ChatMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	RoomId           string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName         string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Content          *MessageContent        `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Mentions         []string               `protobuf:"bytes,7,rep,name=mentions,proto3" json:"mentions,omitempty"`
	ReplyToMessageId string                 `protobuf:"bytes,8,opt,name=reply_to_message_id,json=replyToMessageId,proto3" json:"reply_to_message_id,omitempty"`
	IsEdited         bool                   `protobuf:"varint,9,opt,name=is_edited,json=isEdited,proto3" json:"is_edited,omitempty"`
	EditedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status           MessageStatus          `protobuf:"varint,12,opt,name=status,proto3,enum=wearforce.gateway.v1.MessageStatus" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ChatMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMessage) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ChatMessage) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChatMessage) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *ChatMessage) GetReplyToMessageId() string {
	if x != nil {
		return x.ReplyToMessageId
	}
	return ""
}

func (x *ChatMessage) GetIsEdited() bool {
	if x != nil {
		return x.IsEdited
	}
	return false
}

func (x *ChatMessage) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

func (x *ChatMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ChatMessage) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_PENDING
}

type MessageContent struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Type          MessageContent_ContentType `protobuf:"varint,1,opt,name=type,proto3,enum=wearforce.gateway.v1.MessageContent_ContentType" json:"type,omitempty"`
	Text          string                     `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Media         *MediaContent              `protobuf:"bytes,3,opt,name=media,proto3" json:"media,omitempty"`
	Location      *LocationContent           `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	System        *SystemContent             `protobuf:"bytes,5,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *MessageContent) GetType() MessageContent_ContentType {
	if x != nil {
		return x.Type
	}
	return MessageContent_TEXT
}

func (x *MessageContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageContent) GetMedia() *MediaContent {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *MessageContent) GetLocation() *LocationContent {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *MessageContent) GetSystem() *SystemContent {
	if x != nil {
		return x.System
	}
	return nil
}

type MediaContent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl    string                 `protobuf:"bytes,2,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Filename        string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize        int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType        string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // For audio/video
	Width           int32                  `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`                                            // For images/video
	Height          int32                  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`                                          // For images/video
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MediaContent) Reset() {
	*x = MediaContent{}
	mi := &file_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaContent) ProtoMessage() {}

func (x *MediaContent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaContent.ProtoReflect.Descriptor instead.
func (*MediaContent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

func (x *MediaContent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaContent) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *MediaContent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MediaContent) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MediaContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaContent) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *MediaContent) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaContent) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type LocationContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PlaceName     string                 `protobuf:"bytes,4,opt,name=place_name,json=placeName,proto3" json:"place_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationContent) Reset() {
	*x = LocationContent{}
	mi := &file_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationContent) ProtoMessage() {}

func (x *LocationContent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationContent.ProtoReflect.Descriptor instead.
func (*LocationContent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{14}
}

func (x *LocationContent) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationContent) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationContent) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LocationContent) GetPlaceName() string {
	if x != nil {
		return x.PlaceName
	}
	return ""
}

type SystemContent struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Type          SystemContent_SystemMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=wearforce.gateway.v1.SystemContent_SystemMessageType" json:"type,omitempty"`
	ActorUserId   string                          `protobuf:"bytes,2,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	TargetUserId  string                          `protobuf:"bytes,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	Details       string                          `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemContent) Reset() {
	*x = SystemContent{}
	mi := &file_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemContent) ProtoMessage() {}

func (x *SystemContent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemContent.ProtoReflect.Descriptor instead.
func (*SystemContent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{15}
}

func (x *SystemContent) GetType() SystemContent_SystemMessageType {
	if x != nil {
		return x.Type
	}
	return SystemContent_USER_JOINED
}

func (x *SystemContent) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *SystemContent) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *SystemContent) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ChatUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Status        UserStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=wearforce.gateway.v1.UserStatus" json:"status,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Role          UserRole               `protobuf:"varint,7,opt,name=role,proto3,enum=wearforce.gateway.v1.UserRole" json:"role,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatUser) Reset() {
	*x = ChatUser{}
	mi := &file_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUser) ProtoMessage() {}

func (x *ChatUser) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUser.ProtoReflect.Descriptor instead.
func (*ChatUser) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{16}
}

func (x *ChatUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ChatUser) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ChatUser) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *ChatUser) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_OFFLINE
}

func (x *ChatUser) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *ChatUser) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_MEMBER
}

func (x *ChatUser) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x14wearforce.gateway.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x01\n" +
	"\x0fJoinChatRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12O\n" +
	"\bmetadata\x18\x04 \x03(\v23.wearforce.gateway.v1.JoinChatRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x10JoinChatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12A\n" +
	"\factive_users\x18\x04 \x03(\v2\x1e.wearforce.gateway.v1.ChatUserR\vactiveUsers\"c\n" +
	"\x10LeaveChatRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"R\n" +
	"\x11LeaveChatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xf0\x01\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12>\n" +
	"\acontent\x18\x04 \x01(\v2$.wearforce.gateway.v1.MessageContentR\acontent\x12\x1a\n" +
	"\bmentions\x18\x05 \x03(\tR\bmentions\x12-\n" +
	"\x13reply_to_message_id\x18\x06 \x01(\tR\x10replyToMessageId\"\xad\x01\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x9a\x01\n" +
	"\x15StreamMessagesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x120\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"\xdd\x01\n" +
	"\x15GetChatHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x122\n" +
	"\x06before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\x120\n" +
	"\x05after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05after\"\x93\x01\n" +
	"\x16GetChatHistoryResponse\x12=\n" +
	"\bmessages\x18\x01 \x03(\v2!.wearforce.gateway.v1.ChatMessageR\bmessages\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"I\n" +
	"\x15GetActiveUsersRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"o\n" +
	"\x16GetActiveUsersResponse\x124\n" +
	"\x05users\x18\x01 \x03(\v2\x1e.wearforce.gateway.v1.ChatUserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xdd\x04\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12>\n" +
	"\acontent\x18\x05 \x01(\v2$.wearforce.gateway.v1.MessageContentR\acontent\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bmentions\x18\a \x03(\tR\bmentions\x12-\n" +
	"\x13reply_to_message_id\x18\b \x01(\tR\x10replyToMessageId\x12\x1b\n" +
	"\tis_edited\x18\t \x01(\bR\bisEdited\x127\n" +
	"\tedited_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\beditedAt\x12K\n" +
	"\bmetadata\x18\v \x03(\v2/.wearforce.gateway.v1.ChatMessage.MetadataEntryR\bmetadata\x12;\n" +
	"\x06status\x18\f \x01(\x0e2#.wearforce.gateway.v1.MessageStatusR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x03\n" +
	"\x0eMessageContent\x12D\n" +
	"\x04type\x18\x01 \x01(\x0e20.wearforce.gateway.v1.MessageContent.ContentTypeR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x128\n" +
	"\x05media\x18\x03 \x01(\v2\".wearforce.gateway.v1.MediaContentR\x05media\x12A\n" +
	"\blocation\x18\x04 \x01(\v2%.wearforce.gateway.v1.LocationContentR\blocation\x12;\n" +
	"\x06system\x18\x05 \x01(\v2#.wearforce.gateway.v1.SystemContentR\x06system\"\\\n" +
	"\vContentType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05AUDIO\x10\x02\x12\t\n" +
	"\x05VIDEO\x10\x03\x12\b\n" +
	"\x04FILE\x10\x04\x12\f\n" +
	"\bLOCATION\x10\x05\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x06\"\xf4\x01\n" +
	"\fMediaContent\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12#\n" +
	"\rthumbnail_url\x18\x02 \x01(\tR\fthumbnailUrl\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12)\n" +
	"\x10duration_seconds\x18\x06 \x01(\x05R\x0fdurationSeconds\x12\x14\n" +
	"\x05width\x18\a \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x05R\x06height\"\x84\x01\n" +
	"\x0fLocationContent\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"place_name\x18\x04 \x01(\tR\tplaceName\"\xbc\x02\n" +
	"\rSystemContent\x12I\n" +
	"\x04type\x18\x01 \x01(\x0e25.wearforce.gateway.v1.SystemContent.SystemMessageTypeR\x04type\x12\"\n" +
	"\ractor_user_id\x18\x02 \x01(\tR\vactorUserId\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\tR\ftargetUserId\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\"|\n" +
	"\x11SystemMessageType\x12\x0f\n" +
	"\vUSER_JOINED\x10\x00\x12\r\n" +
	"\tUSER_LEFT\x10\x01\x12\x11\n" +
	"\rUSER_PROMOTED\x10\x02\x12\x10\n" +
	"\fUSER_DEMOTED\x10\x03\x12\x10\n" +
	"\fROOM_CREATED\x10\x04\x12\x10\n" +
	"\fROOM_UPDATED\x10\x05\"\xb0\x03\n" +
	"\bChatUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2 .wearforce.gateway.v1.UserStatusR\x06status\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x122\n" +
	"\x04role\x18\a \x01(\x0e2\x1e.wearforce.gateway.v1.UserRoleR\x04role\x12H\n" +
	"\bmetadata\x18\b \x03(\v2,.wearforce.gateway.v1.ChatUser.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*H\n" +
	"\n" +
	"UserStatus\x12\v\n" +
	"\aOFFLINE\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\x12\b\n" +
	"\x04AWAY\x10\x02\x12\b\n" +
	"\x04BUSY\x10\x03\x12\r\n" +
	"\tINVISIBLE\x10\x04*;\n" +
	"\bUserRole\x12\n" +
	"\n" +
	"\x06MEMBER\x10\x00\x12\r\n" +
	"\tMODERATOR\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02\x12\t\n" +
	"\x05OWNER\x10\x03*K\n" +
	"\rMessageStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\b\n" +
	"\x04SENT\x10\x01\x12\r\n" +
	"\tDELIVERED\x10\x02\x12\b\n" +
	"\x04READ\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xe8\x04\n" +
	"\vChatService\x12Y\n" +
	"\bJoinChat\x12%.wearforce.gateway.v1.JoinChatRequest\x1a&.wearforce.gateway.v1.JoinChatResponse\x12\\\n" +
	"\tLeaveChat\x12&.wearforce.gateway.v1.LeaveChatRequest\x1a'.wearforce.gateway.v1.LeaveChatResponse\x12b\n" +
	"\vSendMessage\x12(.wearforce.gateway.v1.SendMessageRequest\x1a).wearforce.gateway.v1.SendMessageResponse\x12b\n" +
	"\x0eStreamMessages\x12+.wearforce.gateway.v1.StreamMessagesRequest\x1a!.wearforce.gateway.v1.ChatMessage0\x01\x12k\n" +
	"\x0eGetChatHistory\x12+.wearforce.gateway.v1.GetChatHistoryRequest\x1a,.wearforce.gateway.v1.GetChatHistoryResponse\x12k\n" +
	"\x0eGetActiveUsers\x12+.wearforce.gateway.v1.GetActiveUsersRequest\x1a,.wearforce.gateway.v1.GetActiveUsersResponseB(Z&github.com/wearforce/gateway/pkg/protob\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_chat_proto_goTypes = []any{
	(UserStatus)(0),                      // 0: wearforce.gateway.v1.UserStatus
	(UserRole)(0),                        // 1: wearforce.gateway.v1.UserRole
	(MessageStatus)(0),                   // 2: wearforce.gateway.v1.MessageStatus
	(MessageContent_ContentType)(0),      // 3: wearforce.gateway.v1.MessageContent.ContentType
	(SystemContent_SystemMessageType)(0), // 4: wearforce.gateway.v1.SystemContent.SystemMessageType
	(*JoinChatRequest)(nil),              // 5: wearforce.gateway.v1.JoinChatRequest
	(*JoinChatResponse)(nil),             // 6: wearforce.gateway.v1.JoinChatResponse
	(*LeaveChatRequest)(nil),             // 7: wearforce.gateway.v1.LeaveChatRequest
	(*LeaveChatResponse)(nil),            // 8: wearforce.gateway.v1.LeaveChatResponse
	(*SendMessageRequest)(nil),           // 9: wearforce.gateway.v1.SendMessageRequest
	(*SendMessageResponse)(nil),          // 10: wearforce.gateway.v1.SendMessageResponse
	(*StreamMessagesRequest)(nil),        // 11: wearforce.gateway.v1.StreamMessagesRequest
	(*GetChatHistoryRequest)(nil),        // 12: wearforce.gateway.v1.GetChatHistoryRequest
	(*GetChatHistoryResponse)(nil),       // 13: wearforce.gateway.v1.GetChatHistoryResponse
	(*GetActiveUsersRequest)(nil),        // 14: wearforce.gateway.v1.GetActiveUsersRequest
	(*GetActiveUsersResponse)(nil),       // 15: wearforce.gateway.v1.GetActiveUsersResponse
	(*ChatMessage)(nil),                  // 16: wearforce.gateway.v1.ChatMessage
	(*MessageContent)(nil),               // 17: wearforce.gateway.v1.MessageContent
	(*MediaContent)(nil),                 // 18: wearforce.gateway.v1.MediaContent
	(*LocationContent)(nil),              // 19: wearforce.gateway.v1.LocationContent
	(*SystemContent)(nil),                // 20: wearforce.gateway.v1.SystemContent
	(*ChatUser)(nil),                     // 21: wearforce.gateway.v1.ChatUser
	nil,                                  // 22: wearforce.gateway.v1.JoinChatRequest.MetadataEntry
	nil,                                  // 23: wearforce.gateway.v1.ChatMessage.MetadataEntry
	nil,                                  // 24: wearforce.gateway.v1.ChatUser.MetadataEntry
	(*timestamppb.Timestamp)(nil),        // 25: google.protobuf.Timestamp
}
var file_chat_proto_depIdxs = []int32{
	22, // 0: wearforce.gateway.v1.JoinChatRequest.metadata:type_name -> wearforce.gateway.v1.JoinChatRequest.MetadataEntry
	21, // 1: wearforce.gateway.v1.JoinChatResponse.active_users:type_name -> wearforce.gateway.v1.ChatUser
	17, // 2: wearforce.gateway.v1.SendMessageRequest.content:type_name -> wearforce.gateway.v1.MessageContent
	25, // 3: wearforce.gateway.v1.SendMessageResponse.timestamp:type_name -> google.protobuf.Timestamp
	25, // 4: wearforce.gateway.v1.StreamMessagesRequest.since:type_name -> google.protobuf.Timestamp
	25, // 5: wearforce.gateway.v1.GetChatHistoryRequest.before:type_name -> google.protobuf.Timestamp
	25, // 6: wearforce.gateway.v1.GetChatHistoryRequest.after:type_name -> google.protobuf.Timestamp
	16, // 7: wearforce.gateway.v1.GetChatHistoryResponse.messages:type_name -> wearforce.gateway.v1.ChatMessage
	21, // 8: wearforce.gateway.v1.GetActiveUsersResponse.users:type_name -> wearforce.gateway.v1.ChatUser
	17, // 9: wearforce.gateway.v1.ChatMessage.content:type_name -> wearforce.gateway.v1.MessageContent
	25, // 10: wearforce.gateway.v1.ChatMessage.timestamp:type_name -> google.protobuf.Timestamp
	25, // 11: wearforce.gateway.v1.ChatMessage.edited_at:type_name -> google.protobuf.Timestamp
	23, // 12: wearforce.gateway.v1.ChatMessage.metadata:type_name -> wearforce.gateway.v1.ChatMessage.MetadataEntry
	2,  // 13: wearforce.gateway.v1.ChatMessage.status:type_name -> wearforce.gateway.v1.MessageStatus
	3,  // 14: wearforce.gateway.v1.MessageContent.type:type_name -> wearforce.gateway.v1.MessageContent.ContentType
	18, // 15: wearforce.gateway.v1.MessageContent.media:type_name -> wearforce.gateway.v1.MediaContent
	19, // 16: wearforce.gateway.v1.MessageContent.location:type_name -> wearforce.gateway.v1.LocationContent
	20, // 17: wearforce.gateway.v1.MessageContent.system:type_name -> wearforce.gateway.v1.SystemContent
	4,  // 18: wearforce.gateway.v1.SystemContent.type:type_name -> wearforce.gateway.v1.SystemContent.SystemMessageType
	0,  // 19: wearforce.gateway.v1.ChatUser.status:type_name -> wearforce.gateway.v1.UserStatus
	25, // 20: wearforce.gateway.v1.ChatUser.last_seen:type_name -> google.protobuf.Timestamp
	1,  // 21: wearforce.gateway.v1.ChatUser.role:type_name -> wearforce.gateway.v1.UserRole
	24, // 22: wearforce.gateway.v1.ChatUser.metadata:type_name -> wearforce.gateway.v1.ChatUser.MetadataEntry
	5,  // 23: wearforce.gateway.v1.ChatService.JoinChat:input_type -> wearforce.gateway.v1.JoinChatRequest
	7,  // 24: wearforce.gateway.v1.ChatService.LeaveChat:input_type -> wearforce.gateway.v1.LeaveChatRequest
	9,  // 25: wearforce.gateway.v1.ChatService.SendMessage:input_type -> wearforce.gateway.v1.SendMessageRequest
	11, // 26: wearforce.gateway.v1.ChatService.StreamMessages:input_type -> wearforce.gateway.v1.StreamMessagesRequest
	12, // 27: wearforce.gateway.v1.ChatService.GetChatHistory:input_type -> wearforce.gateway.v1.GetChatHistoryRequest
	14, // 28: wearforce.gateway.v1.ChatService.GetActiveUsers:input_type -> wearforce.gateway.v1.GetActiveUsersRequest
	6,  // 29: wearforce.gateway.v1.ChatService.JoinChat:output_type -> wearforce.gateway.v1.JoinChatResponse
	8,  // 30: wearforce.gateway.v1.ChatService.LeaveChat:output_type -> wearforce.gateway.v1.LeaveChatResponse
	10, // 31: wearforce.gateway.v1.ChatService.SendMessage:output_type -> wearforce.gateway.v1.SendMessageResponse
	16, // 32: wearforce.gateway.v1.ChatService.StreamMessages:output_type -> wearforce.gateway.v1.ChatMessage
	13, // 33: wearforce.gateway.v1.ChatService.GetChatHistory:output_type -> wearforce.gateway.v1.GetChatHistoryResponse
	15, // 34: wearforce.gateway.v1.ChatService.GetActiveUsers:output_type -> wearforce.gateway.v1.GetActiveUsersResponse
	29, // [29:35] is the sub-list for method output_type
	23, // [23:29] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
