// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: services.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_services_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_services_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1, 0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=wearforce.gateway.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Details       map[string]string                 `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp            `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ServiceStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Services       []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	IncludeMetrics bool                   `protobuf:"varint,2,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceStatusRequest) Reset() {
	*x = ServiceStatusRequest{}
	mi := &file_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatusRequest) ProtoMessage() {}

func (x *ServiceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatusRequest.ProtoReflect.Descriptor instead.
func (*ServiceStatusRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceStatusRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ServiceStatusRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

type ServiceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceStatus       `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	SystemMetrics *SystemMetrics         `protobuf:"bytes,2,opt,name=system_metrics,json=systemMetrics,proto3" json:"system_metrics,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatusResponse) Reset() {
	*x = ServiceStatusResponse{}
	mi := &file_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatusResponse) ProtoMessage() {}

func (x *ServiceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatusResponse.ProtoReflect.Descriptor instead.
func (*ServiceStatusResponse) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceStatusResponse) GetServices() []*ServiceStatus {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ServiceStatusResponse) GetSystemMetrics() *SystemMetrics {
	if x != nil {
		return x.SystemMetrics
	}
	return nil
}

func (x *ServiceStatusResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ServiceStatus struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Name          string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=wearforce.gateway.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Version       string                            `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        *timestamppb.Timestamp            `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Dependencies  []*Dependency                     `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Metadata      map[string]string                 `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceStatus) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *ServiceStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceStatus) GetUptime() *timestamppb.Timestamp {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *ServiceStatus) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ServiceStatus) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Dependency struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Name          string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // database, service, cache, etc.
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,3,opt,name=status,proto3,enum=wearforce.gateway.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Endpoint      string                            `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	LastCheck     *timestamppb.Timestamp            `protobuf:"bytes,5,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	ErrorMessage  string                            `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{5}
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Dependency) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *Dependency) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Dependency) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

func (x *Dependency) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SystemMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage            float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage         float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	ActiveConnections   int64                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	TotalRequests       int64                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	FailedRequests      int64                  `protobuf:"varint,5,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	AverageResponseTime float64                `protobuf:"fixed64,6,opt,name=average_response_time,json=averageResponseTime,proto3" json:"average_response_time,omitempty"`
	CustomMetrics       map[string]float64     `protobuf:"bytes,7,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{6}
}

func (x *SystemMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemMetrics) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *SystemMetrics) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *SystemMetrics) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *SystemMetrics) GetAverageResponseTime() float64 {
	if x != nil {
		return x.AverageResponseTime
	}
	return 0
}

func (x *SystemMetrics) GetCustomMetrics() map[string]float64 {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

type ForwardRequestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	QueryParams   map[string]string      `protobuf:"bytes,6,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      *RequestMetadata       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequestData) Reset() {
	*x = ForwardRequestData{}
	mi := &file_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequestData) ProtoMessage() {}

func (x *ForwardRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequestData.ProtoReflect.Descriptor instead.
func (*ForwardRequestData) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{7}
}

func (x *ForwardRequestData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ForwardRequestData) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ForwardRequestData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ForwardRequestData) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ForwardRequestData) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ForwardRequestData) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *ForwardRequestData) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ForwardResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponseData) Reset() {
	*x = ForwardResponseData{}
	mi := &file_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponseData) ProtoMessage() {}

func (x *ForwardResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponseData.ProtoReflect.Descriptor instead.
func (*ForwardResponseData) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{8}
}

func (x *ForwardResponseData) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ForwardResponseData) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ForwardResponseData) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ForwardResponseData) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BatchForwardRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Requests          []*ForwardRequestData  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	ParallelExecution bool                   `protobuf:"varint,2,opt,name=parallel_execution,json=parallelExecution,proto3" json:"parallel_execution,omitempty"`
	TimeoutSeconds    int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BatchForwardRequest) Reset() {
	*x = BatchForwardRequest{}
	mi := &file_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchForwardRequest) ProtoMessage() {}

func (x *BatchForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchForwardRequest.ProtoReflect.Descriptor instead.
func (*BatchForwardRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{9}
}

func (x *BatchForwardRequest) GetRequests() []*ForwardRequestData {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *BatchForwardRequest) GetParallelExecution() bool {
	if x != nil {
		return x.ParallelExecution
	}
	return false
}

func (x *BatchForwardRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type BatchForwardResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Responses       []*ForwardResponseData `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Errors          []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	SuccessfulCount int32                  `protobuf:"varint,3,opt,name=successful_count,json=successfulCount,proto3" json:"successful_count,omitempty"`
	FailedCount     int32                  `protobuf:"varint,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchForwardResponse) Reset() {
	*x = BatchForwardResponse{}
	mi := &file_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchForwardResponse) ProtoMessage() {}

func (x *BatchForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchForwardResponse.ProtoReflect.Descriptor instead.
func (*BatchForwardResponse) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{10}
}

func (x *BatchForwardResponse) GetResponses() []*ForwardResponseData {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchForwardResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BatchForwardResponse) GetSuccessfulCount() int32 {
	if x != nil {
		return x.SuccessfulCount
	}
	return 0
}

func (x *BatchForwardResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

type ProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          *anypb.Any             `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	QueryParams   map[string]string      `protobuf:"bytes,5,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      *RequestMetadata       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{11}
}

func (x *ProxyRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProxyRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyRequest) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ProxyRequest) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *ProxyRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          *anypb.Any             `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Metadata      *ResponseMetadata      `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{12}
}

func (x *ProxyResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ProxyResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyResponse) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ProxyResponse) GetMetadata() *ResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RequestMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TraceId       string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,8,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{13}
}

func (x *RequestMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestMetadata) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *RequestMetadata) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RequestMetadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RequestMetadata) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RequestMetadata) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *RequestMetadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ResponseMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	ServiceVersion   string                 `protobuf:"bytes,4,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	TraceId          string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId           string                 `protobuf:"bytes,6,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Tags             map[string]string      `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseMetadata) Reset() {
	*x = ResponseMetadata{}
	mi := &file_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetadata) ProtoMessage() {}

func (x *ResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMetadata.ProtoReflect.Descriptor instead.
func (*ResponseMetadata) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{14}
}

func (x *ResponseMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseMetadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ResponseMetadata) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *ResponseMetadata) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *ResponseMetadata) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ResponseMetadata) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *ResponseMetadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Rate limiting and quota management
type RateLimitRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resource        string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	RequestedTokens int32                  `protobuf:"varint,3,opt,name=requested_tokens,json=requestedTokens,proto3" json:"requested_tokens,omitempty"`
	Window          string                 `protobuf:"bytes,4,opt,name=window,proto3" json:"window,omitempty"` // "1m", "1h", "1d"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RateLimitRequest) Reset() {
	*x = RateLimitRequest{}
	mi := &file_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRequest) ProtoMessage() {}

func (x *RateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRequest.ProtoReflect.Descriptor instead.
func (*RateLimitRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{15}
}

func (x *RateLimitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RateLimitRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *RateLimitRequest) GetRequestedTokens() int32 {
	if x != nil {
		return x.RequestedTokens
	}
	return 0
}

func (x *RateLimitRequest) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

type RateLimitResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Allowed         bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	RemainingTokens int32                  `protobuf:"varint,2,opt,name=remaining_tokens,json=remainingTokens,proto3" json:"remaining_tokens,omitempty"`
	ResetTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=reset_time,json=resetTime,proto3" json:"reset_time,omitempty"`
	RetryAfterMs    int64                  `protobuf:"varint,4,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RateLimitResponse) Reset() {
	*x = RateLimitResponse{}
	mi := &file_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitResponse) ProtoMessage() {}

func (x *RateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitResponse.ProtoReflect.Descriptor instead.
func (*RateLimitResponse) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{16}
}

func (x *RateLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *RateLimitResponse) GetRemainingTokens() int32 {
	if x != nil {
		return x.RemainingTokens
	}
	return 0
}

func (x *RateLimitResponse) GetResetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetTime
	}
	return nil
}

func (x *RateLimitResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type QuotaRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resource        string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	RequestedAmount int64                  `protobuf:"varint,3,opt,name=requested_amount,json=requestedAmount,proto3" json:"requested_amount,omitempty"`
	Period          string                 `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"` // "daily", "monthly", "yearly"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuotaRequest) Reset() {
	*x = QuotaRequest{}
	mi := &file_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaRequest) ProtoMessage() {}

func (x *QuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaRequest.ProtoReflect.Descriptor instead.
func (*QuotaRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{17}
}

func (x *QuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QuotaRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *QuotaRequest) GetRequestedAmount() int64 {
	if x != nil {
		return x.RequestedAmount
	}
	return 0
}

func (x *QuotaRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type QuotaResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Allowed        bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	RemainingQuota int64                  `protobuf:"varint,2,opt,name=remaining_quota,json=remainingQuota,proto3" json:"remaining_quota,omitempty"`
	TotalQuota     int64                  `protobuf:"varint,3,opt,name=total_quota,json=totalQuota,proto3" json:"total_quota,omitempty"`
	ResetTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=reset_time,json=resetTime,proto3" json:"reset_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuotaResponse) Reset() {
	*x = QuotaResponse{}
	mi := &file_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaResponse) ProtoMessage() {}

func (x *QuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaResponse.ProtoReflect.Descriptor instead.
func (*QuotaResponse) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{18}
}

func (x *QuotaResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *QuotaResponse) GetRemainingQuota() int64 {
	if x != nil {
		return x.RemainingQuota
	}
	return 0
}

func (x *QuotaResponse) GetTotalQuota() int64 {
	if x != nil {
		return x.TotalQuota
	}
	return 0
}

func (x *QuotaResponse) GetResetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetTime
	}
	return nil
}

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\x12\x14wearforce.gateway.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xff\x02\n" +
	"\x13HealthCheckResponse\x12O\n" +
	"\x06status\x18\x01 \x01(\x0e27.wearforce.gateway.v1.HealthCheckResponse.ServingStatusR\x06status\x12P\n" +
	"\adetails\x18\x02 \x03(\v26.wearforce.gateway.v1.HealthCheckResponse.DetailsEntryR\adetails\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\"[\n" +
	"\x14ServiceStatusRequest\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\x12'\n" +
	"\x0finclude_metrics\x18\x02 \x01(\bR\x0eincludeMetrics\"\xde\x01\n" +
	"\x15ServiceStatusResponse\x12?\n" +
	"\bservices\x18\x01 \x03(\v2#.wearforce.gateway.v1.ServiceStatusR\bservices\x12J\n" +
	"\x0esystem_metrics\x18\x02 \x01(\v2#.wearforce.gateway.v1.SystemMetricsR\rsystemMetrics\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x94\x03\n" +
	"\rServiceStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12O\n" +
	"\x06status\x18\x02 \x01(\x0e27.wearforce.gateway.v1.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x122\n" +
	"\x06uptime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06uptime\x12D\n" +
	"\fdependencies\x18\x05 \x03(\v2 .wearforce.gateway.v1.DependencyR\fdependencies\x12M\n" +
	"\bmetadata\x18\x06 \x03(\v21.wearforce.gateway.v1.ServiceStatus.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\n" +
	"Dependency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12O\n" +
	"\x06status\x18\x03 \x01(\x0e27.wearforce.gateway.v1.HealthCheckResponse.ServingStatusR\x06status\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x129\n" +
	"\n" +
	"last_check\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xa3\x03\n" +
	"\rSystemMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x03R\x11activeConnections\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x03R\rtotalRequests\x12'\n" +
	"\x0ffailed_requests\x18\x05 \x01(\x03R\x0efailedRequests\x122\n" +
	"\x15average_response_time\x18\x06 \x01(\x01R\x13averageResponseTime\x12]\n" +
	"\x0ecustom_metrics\x18\a \x03(\v26.wearforce.gateway.v1.SystemMetrics.CustomMetricsEntryR\rcustomMetrics\x1a@\n" +
	"\x12CustomMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xe5\x03\n" +
	"\x12ForwardRequestData\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12O\n" +
	"\aheaders\x18\x04 \x03(\v25.wearforce.gateway.v1.ForwardRequestData.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\\\n" +
	"\fquery_params\x18\x06 \x03(\v29.wearforce.gateway.v1.ForwardRequestData.QueryParamsEntryR\vqueryParams\x12A\n" +
	"\bmetadata\x18\a \x01(\v2%.wearforce.gateway.v1.RequestMetadataR\bmetadata\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x02\n" +
	"\x13ForwardResponseData\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12P\n" +
	"\aheaders\x18\x02 \x03(\v26.wearforce.gateway.v1.ForwardResponseData.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12B\n" +
	"\bmetadata\x18\x04 \x01(\v2&.wearforce.gateway.v1.ResponseMetadataR\bmetadata\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x13BatchForwardRequest\x12D\n" +
	"\brequests\x18\x01 \x03(\v2(.wearforce.gateway.v1.ForwardRequestDataR\brequests\x12-\n" +
	"\x12parallel_execution\x18\x02 \x01(\bR\x11parallelExecution\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\xc5\x01\n" +
	"\x14BatchForwardResponse\x12G\n" +
	"\tresponses\x18\x01 \x03(\v2).wearforce.gateway.v1.ForwardResponseDataR\tresponses\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12)\n" +
	"\x10successful_count\x18\x03 \x01(\x05R\x0fsuccessfulCount\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\x05R\vfailedCount\"\xc6\x03\n" +
	"\fProxyRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12I\n" +
	"\aheaders\x18\x03 \x03(\v2/.wearforce.gateway.v1.ProxyRequest.HeadersEntryR\aheaders\x12(\n" +
	"\x04body\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x04body\x12V\n" +
	"\fquery_params\x18\x05 \x03(\v23.wearforce.gateway.v1.ProxyRequest.QueryParamsEntryR\vqueryParams\x12A\n" +
	"\bmetadata\x18\x06 \x01(\v2%.wearforce.gateway.v1.RequestMetadataR\bmetadata\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x02\n" +
	"\rProxyResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12J\n" +
	"\aheaders\x18\x02 \x03(\v20.wearforce.gateway.v1.ProxyResponse.HeadersEntryR\aheaders\x12(\n" +
	"\x04body\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04body\x12B\n" +
	"\bmetadata\x18\x04 \x01(\v2&.wearforce.gateway.v1.ResponseMetadataR\bmetadata\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x03\n" +
	"\x0fRequestMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\b \x01(\tR\x06spanId\x12C\n" +
	"\x04tags\x18\t \x03(\v2/.wearforce.gateway.v1.RequestMetadata.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x02\n" +
	"\x10ResponseMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x03R\x10processingTimeMs\x12'\n" +
	"\x0fservice_version\x18\x04 \x01(\tR\x0eserviceVersion\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x06 \x01(\tR\x06spanId\x12D\n" +
	"\x04tags\x18\a \x03(\v20.wearforce.gateway.v1.ResponseMetadata.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\x10RateLimitRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12)\n" +
	"\x10requested_tokens\x18\x03 \x01(\x05R\x0frequestedTokens\x12\x16\n" +
	"\x06window\x18\x04 \x01(\tR\x06window\"\xb9\x01\n" +
	"\x11RateLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12)\n" +
	"\x10remaining_tokens\x18\x02 \x01(\x05R\x0fremainingTokens\x129\n" +
	"\n" +
	"reset_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tresetTime\x12$\n" +
	"\x0eretry_after_ms\x18\x04 \x01(\x03R\fretryAfterMs\"\x86\x01\n" +
	"\fQuotaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12)\n" +
	"\x10requested_amount\x18\x03 \x01(\x03R\x0frequestedAmount\x12\x16\n" +
	"\x06period\x18\x04 \x01(\tR\x06period\"\xae\x01\n" +
	"\rQuotaResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12'\n" +
	"\x0fremaining_quota\x18\x02 \x01(\x03R\x0eremainingQuota\x12\x1f\n" +
	"\vtotal_quota\x18\x03 \x01(\x03R\n" +
	"totalQuota\x129\n" +
	"\n" +
	"reset_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tresetTime2\xaf\x03\n" +
	"\x0eGatewayService\x12b\n" +
	"\vHealthCheck\x12(.wearforce.gateway.v1.HealthCheckRequest\x1a).wearforce.gateway.v1.HealthCheckResponse\x12k\n" +
	"\x10GetServiceStatus\x12*.wearforce.gateway.v1.ServiceStatusRequest\x1a+.wearforce.gateway.v1.ServiceStatusResponse\x12e\n" +
	"\x0eForwardRequest\x12(.wearforce.gateway.v1.ForwardRequestData\x1a).wearforce.gateway.v1.ForwardResponseData\x12e\n" +
	"\fBatchForward\x12).wearforce.gateway.v1.BatchForwardRequest\x1a*.wearforce.gateway.v1.BatchForwardResponse2\xb5\x04\n" +
	"\x13ServiceProxyService\x12W\n" +
	"\fForwardToCRM\x12\".wearforce.gateway.v1.ProxyRequest\x1a#.wearforce.gateway.v1.ProxyResponse\x12W\n" +
	"\fForwardToERP\x12\".wearforce.gateway.v1.ProxyRequest\x1a#.wearforce.gateway.v1.ProxyResponse\x12W\n" +
	"\fForwardToSTT\x12\".wearforce.gateway.v1.ProxyRequest\x1a#.wearforce.gateway.v1.ProxyResponse\x12W\n" +
	"\fForwardToTTS\x12\".wearforce.gateway.v1.ProxyRequest\x1a#.wearforce.gateway.v1.ProxyResponse\x12X\n" +
	"\rForwardToUser\x12\".wearforce.gateway.v1.ProxyRequest\x1a#.wearforce.gateway.v1.ProxyResponse\x12`\n" +
	"\x15ForwardToNotification\x12\".wearforce.gateway.v1.ProxyRequest\x1a#.wearforce.gateway.v1.ProxyResponseB(Z&github.com/wearforce/gateway/pkg/protob\x06proto3"

var (
	file_services_proto_rawDescOnce sync.Once
	file_services_proto_rawDescData []byte
)

func file_services_proto_rawDescGZIP() []byte {
	file_services_proto_rawDescOnce.Do(func() {
		file_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)))
	})
	return file_services_proto_rawDescData
}

var file_services_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_services_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: wearforce.gateway.v1.HealthCheckResponse.ServingStatus
	(*HealthCheckRequest)(nil),             // 1: wearforce.gateway.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 2: wearforce.gateway.v1.HealthCheckResponse
	(*ServiceStatusRequest)(nil),           // 3: wearforce.gateway.v1.ServiceStatusRequest
	(*ServiceStatusResponse)(nil),          // 4: wearforce.gateway.v1.ServiceStatusResponse
	(*ServiceStatus)(nil),                  // 5: wearforce.gateway.v1.ServiceStatus
	(*Dependency)(nil),                     // 6: wearforce.gateway.v1.Dependency
	(*SystemMetrics)(nil),                  // 7: wearforce.gateway.v1.SystemMetrics
	(*ForwardRequestData)(nil),             // 8: wearforce.gateway.v1.ForwardRequestData
	(*ForwardResponseData)(nil),            // 9: wearforce.gateway.v1.ForwardResponseData
	(*BatchForwardRequest)(nil),            // 10: wearforce.gateway.v1.BatchForwardRequest
	(*BatchForwardResponse)(nil),           // 11: wearforce.gateway.v1.BatchForwardResponse
	(*ProxyRequest)(nil),                   // 12: wearforce.gateway.v1.ProxyRequest
	(*ProxyResponse)(nil),                  // 13: wearforce.gateway.v1.ProxyResponse
	(*RequestMetadata)(nil),                // 14: wearforce.gateway.v1.RequestMetadata
	(*ResponseMetadata)(nil),               // 15: wearforce.gateway.v1.ResponseMetadata
	(*RateLimitRequest)(nil),               // 16: wearforce.gateway.v1.RateLimitRequest
	(*RateLimitResponse)(nil),              // 17: wearforce.gateway.v1.RateLimitResponse
	(*QuotaRequest)(nil),                   // 18: wearforce.gateway.v1.QuotaRequest
	(*QuotaResponse)(nil),                  // 19: wearforce.gateway.v1.QuotaResponse
	nil,                                    // 20: wearforce.gateway.v1.HealthCheckResponse.DetailsEntry
	nil,                                    // 21: wearforce.gateway.v1.ServiceStatus.MetadataEntry
	nil,                                    // 22: wearforce.gateway.v1.SystemMetrics.CustomMetricsEntry
	nil,                                    // 23: wearforce.gateway.v1.ForwardRequestData.HeadersEntry
	nil,                                    // 24: wearforce.gateway.v1.ForwardRequestData.QueryParamsEntry
	nil,                                    // 25: wearforce.gateway.v1.ForwardResponseData.HeadersEntry
	nil,                                    // 26: wearforce.gateway.v1.ProxyRequest.HeadersEntry
	nil,                                    // 27: wearforce.gateway.v1.ProxyRequest.QueryParamsEntry
	nil,                                    // 28: wearforce.gateway.v1.ProxyResponse.HeadersEntry
	nil,                                    // 29: wearforce.gateway.v1.RequestMetadata.TagsEntry
	nil,                                    // 30: wearforce.gateway.v1.ResponseMetadata.TagsEntry
	(*timestamppb.Timestamp)(nil),          // 31: google.protobuf.Timestamp
	(*anypb.Any)(nil),                      // 32: google.protobuf.Any
}
var file_services_proto_depIdxs = []int32{
	0,  // 0: wearforce.gateway.v1.HealthCheckResponse.status:type_name -> wearforce.gateway.v1.HealthCheckResponse.ServingStatus
	20, // 1: wearforce.gateway.v1.HealthCheckResponse.details:type_name -> wearforce.gateway.v1.HealthCheckResponse.DetailsEntry
	31, // 2: wearforce.gateway.v1.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 3: wearforce.gateway.v1.ServiceStatusResponse.services:type_name -> wearforce.gateway.v1.ServiceStatus
	7,  // 4: wearforce.gateway.v1.ServiceStatusResponse.system_metrics:type_name -> wearforce.gateway.v1.SystemMetrics
	31, // 5: wearforce.gateway.v1.ServiceStatusResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: wearforce.gateway.v1.ServiceStatus.status:type_name -> wearforce.gateway.v1.HealthCheckResponse.ServingStatus
	31, // 7: wearforce.gateway.v1.ServiceStatus.uptime:type_name -> google.protobuf.Timestamp
	6,  // 8: wearforce.gateway.v1.ServiceStatus.dependencies:type_name -> wearforce.gateway.v1.Dependency
	21, // 9: wearforce.gateway.v1.ServiceStatus.metadata:type_name -> wearforce.gateway.v1.ServiceStatus.MetadataEntry
	0,  // 10: wearforce.gateway.v1.Dependency.status:type_name -> wearforce.gateway.v1.HealthCheckResponse.ServingStatus
	31, // 11: wearforce.gateway.v1.Dependency.last_check:type_name -> google.protobuf.Timestamp
	22, // 12: wearforce.gateway.v1.SystemMetrics.custom_metrics:type_name -> wearforce.gateway.v1.SystemMetrics.CustomMetricsEntry
	23, // 13: wearforce.gateway.v1.ForwardRequestData.headers:type_name -> wearforce.gateway.v1.ForwardRequestData.HeadersEntry
	24, // 14: wearforce.gateway.v1.ForwardRequestData.query_params:type_name -> wearforce.gateway.v1.ForwardRequestData.QueryParamsEntry
	14, // 15: wearforce.gateway.v1.ForwardRequestData.metadata:type_name -> wearforce.gateway.v1.RequestMetadata
	25, // 16: wearforce.gateway.v1.ForwardResponseData.headers:type_name -> wearforce.gateway.v1.ForwardResponseData.HeadersEntry
	15, // 17: wearforce.gateway.v1.ForwardResponseData.metadata:type_name -> wearforce.gateway.v1.ResponseMetadata
	8,  // 18: wearforce.gateway.v1.BatchForwardRequest.requests:type_name -> wearforce.gateway.v1.ForwardRequestData
	9,  // 19: wearforce.gateway.v1.BatchForwardResponse.responses:type_name -> wearforce.gateway.v1.ForwardResponseData
	26, // 20: wearforce.gateway.v1.ProxyRequest.headers:type_name -> wearforce.gateway.v1.ProxyRequest.HeadersEntry
	32, // 21: wearforce.gateway.v1.ProxyRequest.body:type_name -> google.protobuf.Any
	27, // 22: wearforce.gateway.v1.ProxyRequest.query_params:type_name -> wearforce.gateway.v1.ProxyRequest.QueryParamsEntry
	14, // 23: wearforce.gateway.v1.ProxyRequest.metadata:type_name -> wearforce.gateway.v1.RequestMetadata
	28, // 24: wearforce.gateway.v1.ProxyResponse.headers:type_name -> wearforce.gateway.v1.ProxyResponse.HeadersEntry
	32, // 25: wearforce.gateway.v1.ProxyResponse.body:type_name -> google.protobuf.Any
	15, // 26: wearforce.gateway.v1.ProxyResponse.metadata:type_name -> wearforce.gateway.v1.ResponseMetadata
	31, // 27: wearforce.gateway.v1.RequestMetadata.timestamp:type_name -> google.protobuf.Timestamp
	29, // 28: wearforce.gateway.v1.RequestMetadata.tags:type_name -> wearforce.gateway.v1.RequestMetadata.TagsEntry
	31, // 29: wearforce.gateway.v1.ResponseMetadata.timestamp:type_name -> google.protobuf.Timestamp
	30, // 30: wearforce.gateway.v1.ResponseMetadata.tags:type_name -> wearforce.gateway.v1.ResponseMetadata.TagsEntry
	31, // 31: wearforce.gateway.v1.RateLimitResponse.reset_time:type_name -> google.protobuf.Timestamp
	31, // 32: wearforce.gateway.v1.QuotaResponse.reset_time:type_name -> google.protobuf.Timestamp
	1,  // 33: wearforce.gateway.v1.GatewayService.HealthCheck:input_type -> wearforce.gateway.v1.HealthCheckRequest
	3,  // 34: wearforce.gateway.v1.GatewayService.GetServiceStatus:input_type -> wearforce.gateway.v1.ServiceStatusRequest
	8,  // 35: wearforce.gateway.v1.GatewayService.ForwardRequest:input_type -> wearforce.gateway.v1.ForwardRequestData
	10, // 36: wearforce.gateway.v1.GatewayService.BatchForward:input_type -> wearforce.gateway.v1.BatchForwardRequest
	12, // 37: wearforce.gateway.v1.ServiceProxyService.ForwardToCRM:input_type -> wearforce.gateway.v1.ProxyRequest
	12, // 38: wearforce.gateway.v1.ServiceProxyService.ForwardToERP:input_type -> wearforce.gateway.v1.ProxyRequest
	12, // 39: wearforce.gateway.v1.ServiceProxyService.ForwardToSTT:input_type -> wearforce.gateway.v1.ProxyRequest
	12, // 40: wearforce.gateway.v1.ServiceProxyService.ForwardToTTS:input_type -> wearforce.gateway.v1.ProxyRequest
	12, // 41: wearforce.gateway.v1.ServiceProxyService.ForwardToUser:input_type -> wearforce.gateway.v1.ProxyRequest
	12, // 42: wearforce.gateway.v1.ServiceProxyService.ForwardToNotification:input_type -> wearforce.gateway.v1.ProxyRequest
	2,  // 43: wearforce.gateway.v1.GatewayService.HealthCheck:output_type -> wearforce.gateway.v1.HealthCheckResponse
	4,  // 44: wearforce.gateway.v1.GatewayService.GetServiceStatus:output_type -> wearforce.gateway.v1.ServiceStatusResponse
	9,  // 45: wearforce.gateway.v1.GatewayService.ForwardRequest:output_type -> wearforce.gateway.v1.ForwardResponseData
	11, // 46: wearforce.gateway.v1.GatewayService.BatchForward:output_type -> wearforce.gateway.v1.BatchForwardResponse
	13, // 47: wearforce.gateway.v1.ServiceProxyService.ForwardToCRM:output_type -> wearforce.gateway.v1.ProxyResponse
	13, // 48: wearforce.gateway.v1.ServiceProxyService.ForwardToERP:output_type -> wearforce.gateway.v1.ProxyResponse
	13, // 49: wearforce.gateway.v1.ServiceProxyService.ForwardToSTT:output_type -> wearforce.gateway.v1.ProxyResponse
	13, // 50: wearforce.gateway.v1.ServiceProxyService.ForwardToTTS:output_type -> wearforce.gateway.v1.ProxyResponse
	13, // 51: wearforce.gateway.v1.ServiceProxyService.ForwardToUser:output_type -> wearforce.gateway.v1.ProxyResponse
	13, // 52: wearforce.gateway.v1.ServiceProxyService.ForwardToNotification:output_type -> wearforce.gateway.v1.ProxyResponse
	43, // [43:53] is the sub-list for method output_type
	33, // [33:43] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
		EnumInfos:         file_services_proto_enumTypes,
		MessageInfos:      file_services_proto_msgTypes,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
