# WearForce-Clean Gateway Configuration
# This file contains default configuration values
# Override values using environment variables with GATEWAY_ prefix

server:
  host: "0.0.0.0"
  http_port: 8080
  grpc_port: 8081
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  shutdown_timeout: "10s"
  max_header_bytes: 1048576

tls:
  enabled: false
  min_tls_version: "1.2"
  lets_encrypt:
    enabled: false
    cache_dir: "/tmp/autocert"
    staging: true
    renew_before_days: 30
    # domains: []  # Set via environment
    # email: ""    # Set via environment

jwt:
  keycloak:
    # base_url: ""     # Set via environment - required
    # realm: ""        # Set via environment - required  
    # client_id: ""    # Set via environment
    # client_secret: "" # Set via environment
    jwks_path: "/auth/realms/{realm}/protocol/openid_connect/certs"
    cache_timeout: "5m"
  # issuer: ""         # Set via environment - should match Keycloak realm issuer
  # audience: ""       # Set via environment - typically the client ID
  ttl: "24h"

redis:
  address: "localhost:6379"
  # password: ""  # Set via environment if needed
  db: 0
  pool_size: 10
  max_retries: 3
  idle_timeout: "300s"
  read_timeout: "3s"
  write_timeout: "3s"

services:
  stt:
    # url: ""  # Set via environment
    timeout: "30s"
    max_retries: 3
    retry_backoff: "1s"
    circuit_breaker:
      enabled: true
      max_requests: 100
      interval: "10s"
      timeout: "5s"
      ready_to_trip: 5

  tts:
    # url: ""  # Set via environment  
    timeout: "30s"
    max_retries: 3
    retry_backoff: "1s"
    circuit_breaker:
      enabled: true
      max_requests: 100
      interval: "10s"
      timeout: "5s"
      ready_to_trip: 5

  crm:
    # url: ""  # Set via environment
    timeout: "30s"
    max_retries: 3
    retry_backoff: "1s"

  erp:
    # url: ""  # Set via environment
    timeout: "30s"
    max_retries: 3
    retry_backoff: "1s"

  user:
    # url: ""  # Set via environment
    timeout: "30s"
    max_retries: 3
    retry_backoff: "1s"

  notification:
    # url: ""  # Set via environment
    timeout: "30s"
    max_retries: 3
    retry_backoff: "1s"

rate_limit:
  enabled: true
  default_limits:
    default:
      requests: 100
      window: "1m"
      burst: 20
    "/api/audio/":
      requests: 50
      window: "1m"
      burst: 10
    "/ws":
      requests: 10
      window: "1m"
      burst: 5

tracing:
  enabled: false
  service_name: "wearforce-clean-gateway"
  service_version: "1.0.0"
  environment: "development"
  exporter:
    type: "otlp-http"
    endpoint: "http://localhost:4318/v1/traces"
    # headers: {}  # Set via environment if needed
    insecure: true
  sampling:
    type: "ratio"
    ratio: 0.1
  # resources: {}  # Set via environment if needed

metrics:
  enabled: true
  path: "/metrics"
  port: 9090
  interval: "15s"
  namespace: "wearforce-clean"
  subsystem: "gateway"
  # labels: {}  # Set via environment if needed

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: "10s"
  read_deadline: "60s"
  write_deadline: "10s"
  pong_timeout: "60s"
  ping_period: "54s"
  max_message_size: 524288  # 512KB
  max_connections: 1000
  check_origin: false
  # subprotocols: []  # Set via environment if needed

logging:
  level: "info"
  format: "json"
  output: "stdout"
  # file: ""         # Set via environment if output is "file"
  max_size: 100      # MB
  max_age: 30        # days
  max_backups: 10
  compress: true